apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-prometheus-stack-grafana
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /   # Ensures traffic is routed correctly to /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Disable SSL redirect if using HTTP
    nginx.ingress.kubernetes.io/proxy-body-size: 50m  # Optional: Allows larger request bodies
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /grafana  # Ensure the path is unique to avoid conflicts
        pathType: Prefix
        backend:
          service:
            name: kube-prometheus-stack-grafana
            port:
              number: 80
