apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpro-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host:  # Matches any host
    http:
      paths:
      - path: "/vpro"  # Unique path to avoid conflicts
        pathType: Prefix
        backend:
          service:
            name: my-app  # Replace with your actual service name
            port:
              number: 8080
